/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.*;
import java.util.LinkedList;
import java.util.List;
import static org.mockito.Mockito.*;


public class PersistTest {
 //   @Before public void init(){
   //     Persist persist = mock(Persist.class);
    //}
    @Test public void persistancetestFormNumber0() {
        int result = Persist.persistence(0);
        assertEquals(0, result);
    }

    @Test public void testSpyWithLists(){
        List list = new LinkedList();
        List spyList = spy(list);
        assertEquals("List is empty", 0, list.size());
    }

    @Test public void testSpyWithTwoElements(){
        List list = new LinkedList();
        List spyList = spy(list);
        list.add("one");
        spyList.add("one");
        spyList.add("tow");
        assertEquals(1, list.size());
        assertEquals("List is empty", 1, list.size());
    }
    @Test public void getUIDLength4(){
        Persist persist = mock(Persist.class);
        when(persist.getUID()).thenReturn("XYZ3");
        assertEquals(4, persist.getUID().length());
    }
    @Test public void getUIDContentEqualsToXYZ3(){
        Persist persist = mock(Persist.class);
        when(persist.getUID()).thenReturn("XYZ3");
        assertTrue(persist.getUID().equals("XYZ3"));
    }
}